import { DataSource } from 'typeorm';
import { Brand, BrandStatus } from '../../src/modules/brands/entities/brand.entity';

const brandSeeds: Array<{ name: string; status: BrandStatus }> = [
  { name: 'N6', status: BrandStatus.ACTIVE },
  { name: 'OEM', status: BrandStatus.ACTIVE },
  { name: 'HA NAM', status: BrandStatus.ACTIVE },
  { name: 'Rosata', status: BrandStatus.ACTIVE },
  { name: 'Casio', status: BrandStatus.ACTIVE },
  { name: 'BIGGBEN', status: BrandStatus.ACTIVE },
  { name: 'Haint Boutique', status: BrandStatus.ACTIVE },
  { name: 'Citizen', status: BrandStatus.ACTIVE },
  { name: 'Isla Bonita', status: BrandStatus.ACTIVE },
  { name: "Biti's", status: BrandStatus.ACTIVE },
  { name: 'Titishop', status: BrandStatus.ACTIVE },
  { name: 'MAXIVIC', status: BrandStatus.ACTIVE },
  { name: 'Hiền Trần BOUTIQUE', status: BrandStatus.ACTIVE },
  { name: 'SZone', status: BrandStatus.ACTIVE },
  { name: 'Chiho', status: BrandStatus.ACTIVE },
  { name: 'TRIPLE A', status: BrandStatus.ACTIVE },
  { name: 'WHITE CHIC', status: BrandStatus.ACTIVE },
  { name: 'SOHOGO', status: BrandStatus.ACTIVE },
  { name: 'Hity', status: BrandStatus.ACTIVE },
  { name: 'ANN SARA', status: BrandStatus.ACTIVE },
  { name: 'SITAKI', status: BrandStatus.ACTIVE },
  { name: 'Laceva', status: BrandStatus.ACTIVE },
  { name: 'Azuno', status: BrandStatus.ACTIVE },
  { name: 'ARCTIC HUNTER', status: BrandStatus.ACTIVE },
  { name: 'DINCOX', status: BrandStatus.ACTIVE },
  { name: 'PABNO', status: BrandStatus.ACTIVE },
  { name: 'LALAMIA', status: BrandStatus.ACTIVE },
  { name: 'AIN Closet', status: BrandStatus.ACTIVE },
  { name: 'VONESA', status: BrandStatus.ACTIVE },
  { name: 'Baciami', status: BrandStatus.ACTIVE },
  { name: 'Trường Hải', status: BrandStatus.ACTIVE },
  { name: 'Việt Tiến', status: BrandStatus.ACTIVE },
  { name: 'Novelty', status: BrandStatus.ACTIVE },
  { name: 'Việt Pháp Collection', status: BrandStatus.ACTIVE },
  { name: 'Wannabe', status: BrandStatus.ACTIVE },
  { name: 'HƯƠNG TÂM', status: BrandStatus.ACTIVE },
  { name: 'VICCI', status: BrandStatus.ACTIVE },
  { name: 'Amazing', status: BrandStatus.ACTIVE },
  { name: 'Bee Gee', status: BrandStatus.ACTIVE },
  { name: 'Miley Lingerie', status: BrandStatus.ACTIVE },
  { name: 'UPZ', status: BrandStatus.ACTIVE },
  { name: 'GOKING', status: BrandStatus.ACTIVE },
  { name: 'JAMANO', status: BrandStatus.ACTIVE },
  { name: 'SADOGA', status: BrandStatus.ACTIVE },
  { name: 'TLG Thành Long', status: BrandStatus.ACTIVE },
  { name: 'BIGFOX', status: BrandStatus.ACTIVE },
  { name: 'Mirato', status: BrandStatus.ACTIVE },
  { name: 'BULOVA', status: BrandStatus.ACTIVE },
  { name: 'ARADO FASHION', status: BrandStatus.ACTIVE },
  { name: 'Bobo', status: BrandStatus.ACTIVE },
  { name: 'Freeman', status: BrandStatus.ACTIVE },
  { name: 'Kun93', status: BrandStatus.ACTIVE },
  { name: 'unmei', status: BrandStatus.ACTIVE },
  { name: 'Bering', status: BrandStatus.ACTIVE },
  { name: 'Phúc An Fashion', status: BrandStatus.ACTIVE },
  { name: 'Yamaha', status: BrandStatus.ACTIVE },
  { name: 'LiLiLa', status: BrandStatus.ACTIVE },
  { name: 'CARNIVAL', status: BrandStatus.ACTIVE },
  { name: 'ANANSHOP688', status: BrandStatus.ACTIVE },
  { name: 'Đầm váy Mina', status: BrandStatus.ACTIVE },
  { name: 'lylylorem', status: BrandStatus.ACTIVE },
  { name: 'JONAS & VERUS', status: BrandStatus.ACTIVE },
  { name: 'Fasvin', status: BrandStatus.ACTIVE },
  { name: 'BIG FOX', status: BrandStatus.ACTIVE },
  { name: 'NGADO', status: BrandStatus.ACTIVE },
  { name: 'Obongoo', status: BrandStatus.ACTIVE },
  { name: 'Le Coon', status: BrandStatus.ACTIVE },
  { name: 'Julius', status: BrandStatus.ACTIVE },
  { name: 'LYNUSAN', status: BrandStatus.ACTIVE },
  { name: 'KHATOCO ', status: BrandStatus.ACTIVE },
  { name: 'PI Home Of Beauty', status: BrandStatus.ACTIVE },
  { name: 'Tri’C', status: BrandStatus.ACTIVE },
  { name: 'ĐỒ DA THÀNH LONG TLG', status: BrandStatus.ACTIVE },
  { name: 'Miều Est.2013', status: BrandStatus.ACTIVE },
  { name: 'De Leah', status: BrandStatus.ACTIVE },
  { name: 'Babiboo', status: BrandStatus.ACTIVE },
  { name: 'Boube', status: BrandStatus.ACTIVE },
  { name: 'LVPAI', status: BrandStatus.ACTIVE },
  { name: 'COLO', status: BrandStatus.ACTIVE },
  { name: 'MMLG', status: BrandStatus.ACTIVE },
  { name: 'LuckyJQR', status: BrandStatus.ACTIVE },
  { name: 'WINFA', status: BrandStatus.ACTIVE },
  { name: 'Ares man', status: BrandStatus.ACTIVE },
  { name: 'HERADG', status: BrandStatus.ACTIVE },
  { name: 'Leman', status: BrandStatus.ACTIVE },
  { name: 'Aligro', status: BrandStatus.ACTIVE },
  { name: 'Ngọc Quý', status: BrandStatus.ACTIVE },
  { name: 'THE BILY', status: BrandStatus.ACTIVE },
  { name: 'Sanny House', status: BrandStatus.ACTIVE },
  { name: 'Myqlothing', status: BrandStatus.ACTIVE },
  { name: 'LMCATION', status: BrandStatus.ACTIVE },
  { name: 'TUAN THI', status: BrandStatus.ACTIVE },
  { name: 'OEM', status: BrandStatus.ACTIVE },
  { name: 'P Pinkaha', status: BrandStatus.ACTIVE },
  { name: 'D Danido', status: BrandStatus.ACTIVE },
  { name: '2NDDATE', status: BrandStatus.ACTIVE },
  { name: 'Routine', status: BrandStatus.ACTIVE },
  { name: 'Mebra', status: BrandStatus.ACTIVE },
  { name: 'NAVIVU', status: BrandStatus.ACTIVE },
  { name: 'Legaxi', status: BrandStatus.ACTIVE },
  { name: 'Huy Hoàng', status: BrandStatus.ACTIVE },
  { name: 'SURE FASHION S', status: BrandStatus.ACTIVE },
  { name: 'Hương quế', status: BrandStatus.ACTIVE },
  { name: 'MAYHOMES', status: BrandStatus.ACTIVE },
  { name: 'BABOYKA', status: BrandStatus.ACTIVE },
  { name: 'OLEVS', status: BrandStatus.ACTIVE },
  { name: 'MRM Manlywear', status: BrandStatus.ACTIVE },
  { name: 'HABERMAN', status: BrandStatus.ACTIVE },
  { name: 'Tifalu', status: BrandStatus.ACTIVE },
  { name: 'TOMAN', status: BrandStatus.ACTIVE },
  { name: 'Sportslink', status: BrandStatus.ACTIVE },
  { name: 'AGE2X', status: BrandStatus.ACTIVE },
  { name: 'Song An Eco', status: BrandStatus.ACTIVE },
  { name: 'Thủy Hòa', status: BrandStatus.ACTIVE },
  { name: 'Luna Llena', status: BrandStatus.ACTIVE },
  { name: 'Emspo', status: BrandStatus.ACTIVE },
  { name: 'SRWATCH', status: BrandStatus.ACTIVE },
  { name: 'May 10', status: BrandStatus.ACTIVE },
  { name: 'Just Feel Free', status: BrandStatus.ACTIVE },
  { name: 'Omega', status: BrandStatus.ACTIVE },
  { name: 'Vincy', status: BrandStatus.ACTIVE },
  { name: 'RANVERBAE', status: BrandStatus.ACTIVE },
  { name: 'AVOCA', status: BrandStatus.ACTIVE },
  { name: 'Gold Rhino', status: BrandStatus.ACTIVE },
  { name: 'LUPERI', status: BrandStatus.ACTIVE },
  { name: 'LAAS', status: BrandStatus.ACTIVE },
  { name: 'MySun', status: BrandStatus.ACTIVE },
  { name: 'Comfybaby', status: BrandStatus.ACTIVE },
  { name: 'GENVIET JEANS', status: BrandStatus.ACTIVE },
  { name: 'MXM', status: BrandStatus.ACTIVE },
  { name: 'Aetrex', status: BrandStatus.ACTIVE },
  { name: 'Aligo', status: BrandStatus.ACTIVE },
  { name: 'Diệu Tâm', status: BrandStatus.ACTIVE },
  { name: 'No', status: BrandStatus.ACTIVE },
  { name: 'Triumph', status: BrandStatus.ACTIVE },
  { name: 'ORSIL', status: BrandStatus.ACTIVE },
  { name: 'CeCe CiCi', status: BrandStatus.ACTIVE },
  { name: 'DLX', status: BrandStatus.ACTIVE },
  { name: 'SEVENMOOONS', status: BrandStatus.ACTIVE },
  { name: 'DREAMII', status: BrandStatus.ACTIVE },
  { name: 'Skagen', status: BrandStatus.ACTIVE },
  { name: 'AAA', status: BrandStatus.ACTIVE },
  { name: 'HAKI', status: BrandStatus.ACTIVE },
  { name: 'Hạnh Dương', status: BrandStatus.ACTIVE },
  { name: 'Skechers', status: BrandStatus.ACTIVE },
  { name: 'COROS', status: BrandStatus.ACTIVE },
  { name: 'Monobo', status: BrandStatus.ACTIVE },
  { name: 'AAA JEANS', status: BrandStatus.ACTIVE },
  { name: 'NIU24', status: BrandStatus.ACTIVE },
  { name: 'CAN THO AO DAI AO BA BA', status: BrandStatus.ACTIVE },
  { name: 'jones', status: BrandStatus.ACTIVE },
  { name: 'Tropicana', status: BrandStatus.ACTIVE },
  { name: 'Uniman', status: BrandStatus.ACTIVE },
  { name: 'TIEN ANH HOUSE', status: BrandStatus.ACTIVE },
  { name: 'Inujirushi', status: BrandStatus.ACTIVE },
  { name: 'HT SYS', status: BrandStatus.ACTIVE },
  { name: 'MAX DESI', status: BrandStatus.ACTIVE },
  { name: 'SiPU', status: BrandStatus.ACTIVE },
  { name: 'US ARMY', status: BrandStatus.ACTIVE },
  { name: 'PONY', status: BrandStatus.ACTIVE },
  { name: 'CATRIO', status: BrandStatus.ACTIVE },
  { name: 'PGM', status: BrandStatus.ACTIVE },
  { name: 'Zonbig', status: BrandStatus.ACTIVE },
  { name: 'OVERCO', status: BrandStatus.ACTIVE },
  { name: 'SOMIANTON', status: BrandStatus.ACTIVE },
  { name: 'AOLIKES', status: BrandStatus.ACTIVE },
  { name: 'FWD', status: BrandStatus.ACTIVE },
  { name: 'U & YABY', status: BrandStatus.ACTIVE },
  { name: 'MANGO', status: BrandStatus.ACTIVE },
  { name: 'DOGA', status: BrandStatus.ACTIVE },
  { name: 'Derosa Kids', status: BrandStatus.ACTIVE },
  { name: 'Muidoi', status: BrandStatus.ACTIVE },
  { name: 'Marguerite', status: BrandStatus.ACTIVE },
  { name: 'AATH', status: BrandStatus.ACTIVE },
  { name: 'Roman', status: BrandStatus.ACTIVE },
  { name: 'RBI', status: BrandStatus.ACTIVE },
  { name: 'HAHANCO', status: BrandStatus.ACTIVE },
  { name: 'comman', status: BrandStatus.ACTIVE },
  { name: 'TOMI', status: BrandStatus.ACTIVE },
  { name: 'F2 Fashion', status: BrandStatus.ACTIVE },
  { name: 'Merries', status: BrandStatus.ACTIVE },
  { name: 'lorencia', status: BrandStatus.ACTIVE },
  { name: 'Laliz', status: BrandStatus.ACTIVE },
  { name: 'MINIIN', status: BrandStatus.ACTIVE },
  { name: 'TP Tiến Phát SMART', status: BrandStatus.ACTIVE },
  { name: 'Chí Phèo', status: BrandStatus.ACTIVE },
  { name: 'No Brand', status: BrandStatus.ACTIVE },
  { name: 'Siiden', status: BrandStatus.ACTIVE },
  { name: 'Movado', status: BrandStatus.ACTIVE },
  { name: 'SAM Leather', status: BrandStatus.ACTIVE },
  { name: 'ATNKADDS', status: BrandStatus.ACTIVE },
  { name: 'ROSAVAN', status: BrandStatus.ACTIVE },
  { name: 'Brave Person', status: BrandStatus.ACTIVE },
  { name: 'Desmiit', status: BrandStatus.ACTIVE },
  { name: 'FTAKY', status: BrandStatus.ACTIVE },
  { name: 'Converse', status: BrandStatus.ACTIVE },
  { name: 'CLEACCO', status: BrandStatus.ACTIVE },
  { name: 'Vinaci ', status: BrandStatus.ACTIVE },
  { name: 'Adda', status: BrandStatus.ACTIVE },
  { name: 'TLG', status: BrandStatus.ACTIVE },
  { name: 'LQ luxury', status: BrandStatus.ACTIVE },
  { name: 'Hiye', status: BrandStatus.ACTIVE },
  { name: 'Sport1', status: BrandStatus.ACTIVE },
  { name: 'Kito', status: BrandStatus.ACTIVE },
  { name: 'Guess', status: BrandStatus.ACTIVE },
  { name: 'Huệ Ngân', status: BrandStatus.ACTIVE },
  { name: 'CEO', status: BrandStatus.ACTIVE },
  { name: 'DIZIZID', status: BrandStatus.ACTIVE },
  { name: 'Sport', status: BrandStatus.ACTIVE },
  { name: 'Spenco', status: BrandStatus.ACTIVE },
  { name: 'Xưởng Mộc Việt', status: BrandStatus.ACTIVE },
  { name: 'MĐ', status: BrandStatus.ACTIVE },
  { name: 'doukou', status: BrandStatus.ACTIVE },
  { name: 'AFRO', status: BrandStatus.ACTIVE },
  { name: 'Belly Bandit', status: BrandStatus.ACTIVE },
  { name: 'X9', status: BrandStatus.ACTIVE },
  { name: 'ThoiTrangXinh', status: BrandStatus.ACTIVE },
  { name: 'Fashy ', status: BrandStatus.ACTIVE },
  { name: 'VAC ', status: BrandStatus.ACTIVE },
  { name: 'ĐŨI VIỆT', status: BrandStatus.ACTIVE },
  { name: 'Milliken Tampe', status: BrandStatus.ACTIVE },
  { name: 'Garco 10', status: BrandStatus.ACTIVE },
  { name: 'XBags', status: BrandStatus.ACTIVE },
  { name: 'Cộng Cà phê', status: BrandStatus.ACTIVE },
  { name: 'KAVI', status: BrandStatus.ACTIVE },
  { name: 'BH Kids', status: BrandStatus.ACTIVE },
  { name: 'Jobelli', status: BrandStatus.ACTIVE },
  { name: 'ROGTZ', status: BrandStatus.ACTIVE },
  { name: 'Vilady', status: BrandStatus.ACTIVE },
  { name: 'VIMOS', status: BrandStatus.ACTIVE },
  { name: 'Braven', status: BrandStatus.ACTIVE },
  { name: 'MRVUI', status: BrandStatus.ACTIVE },
  { name: 'Maxivic Boutique', status: BrandStatus.ACTIVE },
  { name: 'AUKULASIC', status: BrandStatus.ACTIVE },
  { name: 'Amalife', status: BrandStatus.ACTIVE },
  { name: 'PEAFLO', status: BrandStatus.ACTIVE },
  { name: 'FATRALY', status: BrandStatus.ACTIVE },
  { name: 'DR.MED ', status: BrandStatus.ACTIVE },
  { name: 'OLV ', status: BrandStatus.ACTIVE },
  { name: 'Salomon', status: BrandStatus.ACTIVE },
  { name: 'Anton', status: BrandStatus.ACTIVE },
  { name: 'COTONFIO', status: BrandStatus.ACTIVE },
  { name: 'BEDDYBEAR [Bei Ju Xiong: cốc, gấu]', status: BrandStatus.ACTIVE },
  { name: 'Bạc Hiểu Minh', status: BrandStatus.ACTIVE },
  { name: 'Zento', status: BrandStatus.ACTIVE },
  { name: 'KINGNUOS', status: BrandStatus.ACTIVE },
  { name: 'nOor', status: BrandStatus.ACTIVE },
  { name: 'Phúc An', status: BrandStatus.ACTIVE },
  { name: 'KUNBE', status: BrandStatus.ACTIVE },
  { name: 'Starke', status: BrandStatus.ACTIVE },
  { name: 'BONCHOP', status: BrandStatus.ACTIVE },
  { name: 'SUUNTO', status: BrandStatus.ACTIVE },
  { name: 'Ruzimay Style', status: BrandStatus.ACTIVE },
  { name: 'Infantry', status: BrandStatus.ACTIVE },
  { name: 'Vua Dép Lốp', status: BrandStatus.ACTIVE },
  { name: 'Wonlex', status: BrandStatus.ACTIVE },
  { name: 'Sabina', status: BrandStatus.ACTIVE },
  { name: 'Michael Kors', status: BrandStatus.ACTIVE },
  { name: 'Peak', status: BrandStatus.ACTIVE },
  { name: 'KHATOKO', status: BrandStatus.ACTIVE },
  { name: 'Lotusman', status: BrandStatus.ACTIVE },
  { name: 'Alcatroz', status: BrandStatus.ACTIVE },
  { name: 'miDoctor', status: BrandStatus.ACTIVE },
  { name: 'Innostyle', status: BrandStatus.ACTIVE },
  { name: 'Burny', status: BrandStatus.ACTIVE },
  { name: 'Q&Q', status: BrandStatus.ACTIVE },
  { name: 'Misaki', status: BrandStatus.ACTIVE },
  { name: 'DAVIE', status: BrandStatus.ACTIVE },
  { name: 'idée', status: BrandStatus.ACTIVE },
  { name: 'CAVARA', status: BrandStatus.ACTIVE },
  { name: 'T&D', status: BrandStatus.ACTIVE },
  { name: '360 Boutique', status: BrandStatus.ACTIVE },
  { name: 'DAICAT', status: BrandStatus.ACTIVE },
  { name: 'UNIGREEN', status: BrandStatus.ACTIVE },
  { name: 'ZooZoo', status: BrandStatus.ACTIVE },
  { name: 'NAVICOM', status: BrandStatus.ACTIVE },
];

export async function seedBrands(dataSource: DataSource) {
  const repo = dataSource.getRepository(Brand);

  for (const seed of brandSeeds) {
    const name = seed.name.trim();

    const existing = await repo.findOne({ where: { name } });

    if (existing) {
      continue;
    }

    const brand = repo.create(seed);
    await repo.save(brand);
  }

  console.log('✅ Brand seed data inserted successfully.');
}
