import { ApiProperty } from '@nestjs/swagger';
import { TrendDirection } from '../../interfaces/stats.types';

export class TrendMetricDto {
  @ApiProperty({ example: 125000000, description: 'Current metric value for the range' })
  value!: number;

  @ApiProperty({ example: 98000000, description: 'Previous metric value used for comparison' })
  previousValue!: number;

  @ApiProperty({ example: 27.55, description: 'Percentage change compared to previous period' })
  percentageChange!: number;

  @ApiProperty({ enum: ['up', 'down', 'neutral'], description: 'Direction of the trend' })
  trend!: TrendDirection;
}

export class StatsOverviewResponseDto {
  @ApiProperty({ type: TrendMetricDto })
  revenue!: TrendMetricDto;

  @ApiProperty({ type: TrendMetricDto })
  orders!: TrendMetricDto;

  @ApiProperty({ type: TrendMetricDto })
  customers!: TrendMetricDto;
}

export class RevenueChartPointDto {
  @ApiProperty({ example: '2025-12-02', description: 'ISO date representing the bucket key' })
  date!: string;

  @ApiProperty({ example: 15800000, description: 'Total revenue for the bucket' })
  revenue!: number;

  @ApiProperty({ example: 32, description: 'Total orders counted for the bucket' })
  orderCount!: number;
}

export class OrderStatusSliceDto {
  @ApiProperty({ example: 'Đang xử lý' })
  label!: string;

  @ApiProperty({ example: 'pending', description: 'Status shorthand used internally' })
  status!: string;

  @ApiProperty({ example: 45, description: 'Total orders that belong to this status bucket' })
  value!: number;
}

export class TopSellingProductDto {
  @ApiProperty({ example: 123 })
  productId!: number;

  @ApiProperty({ example: 'Áo sơ mi Linen' })
  name!: string;

  @ApiProperty({
    required: false,
    nullable: true,
    example: 'https://cdn.example.com/products/123.jpg',
  })
  image?: string | null;

  @ApiProperty({ example: 156, description: 'Units sold in the selected range' })
  soldQuantity!: number;

  @ApiProperty({ example: 45000000, description: 'Revenue generated by the product in the range' })
  totalRevenue!: number;
}

export class LowStockProductDto {
  @ApiProperty({ example: 321 })
  productId!: number;

  @ApiProperty({ example: 'Quần Linen Signature' })
  name!: string;

  @ApiProperty({
    required: false,
    nullable: true,
    example: 'https://cdn.example.com/products/321.jpg',
  })
  image?: string | null;

  @ApiProperty({ example: 4, description: 'Total units currently available' })
  stock!: number;

  @ApiProperty({
    required: false,
    nullable: true,
    example: 2,
    description: 'Branch ID where the stock level applies',
  })
  branchId?: number | null;
}

export class ViewLeaderboardItemDto {
  @ApiProperty({ example: 456 })
  id!: number;

  @ApiProperty({ example: 'Bài viết Spotlight mùa thu' })
  name!: string;

  @ApiProperty({ example: 1288 })
  views!: number;

  @ApiProperty({
    required: false,
    nullable: true,
    example: 'https://cdn.example.com/articles/456.jpg',
  })
  image?: string | null;

  @ApiProperty({ enum: ['product', 'article'], description: 'Type of the leaderboard entry' })
  type!: 'product' | 'article';
}
